version: "3.9"
services:
  web:
    links:
      - "db:db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://easeservice:easeservice@db:5432/tattoo_python
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=easeservice
      - POSTGRES_PASSWORD=easeservice
      - POSTGRES_DB=tattoo_python
    expose:
      - 5432
    restart: always